# vim: set ts=2 sw=2 et:
dokuwiki_version: 2020-07-29
dokuwiki_checksum: md5:8867b6a5d71ecb5203402fe5e8fa18c9
dokuwiki_sites:
  - domain: politique.wiki
    config: politique-wiki
    ip: 192.168.50.10
  - domain: recettes.wiki
    config: recettes-wiki
    ip: 192.168.50.10

# ces variables sont définies dans vault.yml
extrauser_username: 
extrauser_password: 

nextcloud_db_system: "mysql"
nextcloud_db_host: "192.168.50.20"
nextcloud_db_name: "nextcloud_db"
nextcloud_custom_cert: false
nextcloud_create_self_signed_cert: false


mariadb_databases:
  - name: nextcloud_db
    encoding: utf8

mariadb_users:
  - name: nextcloud_6
    password: nextcloud_pass
    priv: '*.*:ALL,GRANT'