# Play
- hosts: role_hosting

  vars: 
    required_packages:
      - apache2
      - php7.4

  tasks:

    - name : Install packages
      apt:
        name:
          - apache2
          - php7.3
    
    - name : Create dokuwiki directory
      file :
        path: /usr/src/dokuwiki
        state: directory
        mode: '0755'

    - name : download dokuwiki
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src/dokuwiki
    
    - name : dezip
      unarchive:
        src: /usr/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src/dokuwiki
        remote_src: yes

    - name : get dezipped name
      shell:
        cmd: ls /usr/src/dokuwiki
      register: list

    - name : debug
      debug: 
        var: list

    - name : mv dokuwiki
      copy:
        src: "/usr/src/dokuwiki/{{list[0]}}"
        dest: '/usr/src/dokuwiki/dokuwiki'
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0755'