# Play
- hosts: app_hosting

  tasks:

    - name : Install packages
      apt:
        name:
          - apache2
          - php7.3
    
    - name : Create dokuwiki directory
      file :
        path: /usr/src/dokuwiki
        state: directory
        mode: '0755'

    - name : download dokuwiki
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src/dokuwiki
    
    - name : dezip
      unarchive:
        src: /usr/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src/dokuwiki
        remote_src: yes
      register: dezip_test

    - name: debug dzip
      debug:
        var: dezip_test

    # - name : get dezipped name
    #   shell:
    #     cmd: ls /usr/src/dokuwiki
    #   register: list

    # - name : debug
    #   debug: 
    #     var: list

    - name : mv dokuwiki
      shell:
        cmd : "mv /usr/src/dokuwiki/dokuwiki-2020-07-29 /usr/src/dokuwiki/dokuwiki"
        creates: /usr/src/dokuwiki/dokuwiki/
    
    - name : 'Create folders'
      file:
        path: "/var/www/{{item}}"
        state: directory
        mode: '0755'
      with_items: "{{ sites }}"
        # - recettes.wiki
        # - politique.wiki

    - name : 'Copy dokuwiki in 2 directories'
      shell:
        cmd: "cp -r /usr/src/dokuwiki/dokuwiki/. /var/www/{{item}}"
      with_items: "{{ sites }}"
        # - recettes.wiki
        # - politique.wiki

    - name : 'Give access'
      file:
        path: "/var/www/{{item}}"
        recurse: yes
        owner: www-data
        group: www-data
      with_items: "{{ sites }}"
        # - recettes.wiki
        # - politique.wiki

    - name : 'move wiki conf'
      copy:
        src: 'files/{{item}}'
        dest: '/etc/apache2/sites-available/{{item}}'
      with_items: "{{ conf }}"
        # - politique-wiki.conf
        # - recettes-wiki.conf
    
    - name : 'Activate a2ensite'
      shell:
        cmd: "a2ensite {{item}}"
      with_items: "{{ conf_folder }}"
        # - recettes-wiki
        # - politique-wiki
    
    - name : 'systemCtl'
      shell:
        cmd: "systemctl reload apache2"
    
    - name : 'check if DNS exists'
      shell:
        cmd: "grep -c \"^127.0.0.1 {{item}}\" /etc/hosts || true"
      with_items: "{{ sites }}"
        # - recettes.wiki
        # - politique.wiki
      register: test_host

    - name : debug test_host
      debug: 
        var: test_host

    - name : 'write new hosts'
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 {{item}}"
      with_items: "{{ sites }}"
        # - recettes.wiki
        # - politique.wiki
      when: test_host.results[0].stdout == "0"